config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'

  resources :tweets do
    resources :comments
  end

  get 'tweets/all/:id', to: 'tweets#all', as: :tweets_all

  get 'users/signup', to: 'users#new'
  resources :users, except: :new

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  MAX_BODY_LENGTH = 140
  belongs_to :tweet
  belongs_to :user

  validates :body, presence: true, length: { maximum: MAX_BODY_LENGTH }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  MAX_CONTENT_LENGTH = 140
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :content, presence: true, length: { maximum: MAX_CONTENT_LENGTH }
end

app/models/user.rb
class User < ApplicationRecord
  MAX_NAME_LENGTH = 255
  MAX_EMAIL_LENGTH = 50
  MIN_PASSWORD_LENGTH = 6
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_secure_password

  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_save :email_to_downcase

  validates :name, presence: true, length: { maximum: MAX_NAME_LENGTH }
  validates :email, presence: true, length: { maximum: MAX_EMAIL_LENGTH },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: MIN_PASSWORD_LENGTH }

  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    session_notice(:danger, 'You must be logged in!', login_path) unless logged_in?

    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.build
  end

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def edit
    session_notice(:danger, 'You must be logged in!', login_path) unless logged_in?

    @comment = Comment.find(params[:id])

    if logged_in?
      session_notice(:danger, 'Wrong User') unless equal_with_current_user?(@comment.user)
    end

    @tweet = @comment.tweet
  end

  def update
    comment = Comment.find(params[:id])

    if comment.update(comment_params)
      redirect_to comment.tweet
    else
      render :edit
    end
  end

  def destroy
    session_notice(:danger, 'You must be logged in!', login_path) unless logged_in?

    comment = Comment.find(params[:id])

    if equal_with_current_user?(comment.user)
      comment.destroy
      redirect_to comment.tweet
    else
      session_notice(:danger, 'Wrong User')
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session_notice(:warning, 'Already logged in!') if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = "Welcome #{user.name} !"
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :find_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Tweet.all.order('created_at DESC')
  end

  def all
    @tweets = Tweet.all
    @user = User.find(params[:id])
  end

  def show
  end

  def new
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    if @tweet.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def edit
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    if logged_in?
      session_notice(:danger, 'Wrong User') unless equal_with_current_user?(@tweet.user)
    end
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet
    else
      render :edit
    end
  end

  def destroy
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    if equal_with_current_user?(tweet.user)
      tweet.destroy
      redirect_to tweets_path
    else
      session_notice(:danger, 'Wrong User')
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:user, :content)
  end

  def find_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    session_notice(:warning, 'Already logged in!') if logged_in?

    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def session_notice(type, message, path = root_path)
    flash[type.to_sym] = message
    redirect_to path and return
  end

  def equal_with_current_user?(other_user)
    current_user == other_user
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="column is-10 is-offset-2 comment">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.name %></strong> <small> - <%= time_ago_in_words(comment.created_at) %> ago </small>
          <br>
          <%= comment.body %>
        </p>
      </div>
      <nav class="level is-mobile">
        <div class="level-left">
          <%= link_to edit_tweet_comment_path(comment.tweet, comment), class: 'level-item' do %>
            <span class="icon is-small"><i class="fas fa-edit"></i></span>
          <% end %>
          <%= link_to tweet_comment_path(comment.tweet, comment), method: :delete, class: 'level-item', data: { confirm: 'Are you sure you want to delete this comment?' } do %>
            <span class="icon is-small"><i class="fas fa-trash-alt"></i></span>
          <% end %>
        </div>
      </nav>
    </div>
  </article>
</div>

app/views/comments/_form.html.erb
<div class="container">
  <div class="miltiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-4">
        <h1><%= title %></h1>
      </div>
    </div>
    <div class="column is-4 is-offset-4">
      <article class="media">
        <div class="media-content">
          <%= form_with model: [tweet, comment], local: true do |form| %>
            <div class="control">
              <p class="control">
                    <%= form.label :comment, class: 'label is-large' %>
                    <%= form.text_area :body, class: 'textarea is-large', placeholder: 'Your comment' %><br>
                <p class="control">
                    <%= form.submit submit, class: 'button is-success' %>
                    <%= link_to 'Cancel', tweet, class: 'button is-danger' %>
                </p>
              </p>
            </div>
            <br>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<%= render 'form',
tweet: @tweet,
comment: @comment,
title: "Edit #{@tweet.user.name}'s comment",
submit: 'Update Comment' %>

app/views/comments/new.html.erb
<%= render 'form',
tweet: @tweet,
comment: @comment,
title: "#{current_user.name} - New Comment",
submit: 'Comment' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <section class="section">
    <div class="container">
      <%= render 'shared/nav_bar' %>
      <br>
      <%= render 'shared/flash' %>
      <h2 class="subtitle">
        <%= yield %>
      </h2>
    </div>
  </section>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="container">
  <div class="columns is-multiline">
    <% flash.each do |name, msg| -%>

    <div class="column is-8 is-offset-2">
      <div class="notification has-text-centered is-<%= name %>">
        <%= msg %>
      </div>
    </div>

    <% end -%>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<nav class="navbar is-spaced is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to image_tag('https://logos-marcas.com/wp-content/uploads/2020/04/Twitter-Logo-650x366.png', width: 100) %>
    <%= link_to 'TwitterClone', root_path, class: 'navbar-item is-size-2 is-italic' %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navBar">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navBar" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if logged_in? %>
            <%= link_to 'New Tweet', new_tweet_path, class: 'button is-info has-text-weight-bold' %>
            <%= link_to "Log Out", logout_path, method: :delete, class: "button is-danger has-text-weight-bold" %>
          <% else %>
            <%= link_to "Log In", login_path, class: "button is-info has-textweight-bold" %>
            <%= link_to "Sign Up", users_signup_path, class: "button is-primary hastext-weight-bold" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<div class="container">
  <div class="miltiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-4">
        <h1 class="title has-text-centered"><%= title %></h1>
      </div>
    </div>

    <% if tweet.errors.any? %>
      <div id='error_explanation'>
        <h2>
          <%= pluralize(tweet.errors.count, 'error') %> prohibited this tweet from being saved:
        </h2>
        <ul>
          <% tweet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="column is-4 is-offset-4">
      <%= form_with model: tweet, local: true do |form| %>
        <div class="control">
          <p>
            <%= form.label :content, class: 'label is-large' %>
            <%= form.text_area :content, class: 'textarea is-large', placeholder: 'Your content' %><br>
          </p>
        </div>
        <div class="control">
          <p>
            <%= form.submit submit, class: 'button is-success' %>
            <%= link_to 'Cancel', tweet, class: 'button is-danger' %>
          </p>
        </div>
        <br>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="card block">
  <header class="card-header">
    <% if local_assigns[:index_user] %>
      <p class="card-header-title has-background-grey-light">
        <%= tweet.user.name %>
      </p>
    <% end %>
  </header>
  <div class="card-content">
    <div class="content">
      <p>
        <%= tweet.content %>
      </p>
    </div>
  </div>
  <nav class="level-right">
    <div class="level">
      <span class="is-size-6 is-italic">
        <%= tweet.updated_at.localtime.strftime("%B %d, %Y - %H:%M") %>
      </span>
    </div>
  </nav>
  <footer class="card-footer">
        <% unless local_assigns[:index_user] %>
          <%= link_to root_path, class: 'card-footer-item' do %>
            <span class="icon is-small"><i class="fas fa-hand-point-left"></i></span>
          <% end %>
        <% else %>
          <%= link_to tweet_path(tweet), class: 'card-footer-item' do %>
            <span class="icon is-small"><i class="fas fa-eye"></i></span>
          <% end %>
        <% end %>

        <% if local_assigns[:index_user] && logged_in? %>
          <%= link_to new_tweet_comment_path(tweet), class: 'card-footer-item' do %>
            <span class="icon is-small"><i class="fas fa-comment-medical"></i></span>
          <% end %>
        <% end %>

        <%= link_to tweets_all_path(tweet.user), class: 'card-footer-item' do %>
          <span class="icon is-small"><i class="fab fa-twitter"></i></span>
        <% end %>

        <% if logged_in? && equal_with_current_user?(tweet.user) %>
          <%= link_to edit_tweet_path(tweet), class: 'card-footer-item' do %>
            <span class="icon is-small"><i class="fas fa-edit"></i></span>
          <% end %>
        <% end %>

        <% if logged_in? && equal_with_current_user?(tweet.user) %>
          <%= link_to tweet_path(tweet), class: 'card-footer-item',
            method: :delete, data: { confirm: 'Are you sure you want to delete this tweet?' } do %>
            <span class="icon is-small"><i class="fas fa-trash"></i></span>
          <% end %>
        <% end %>
  </footer>
</div>

app/views/tweets/all.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-4">
        <h1 class="title has-text-centered"> <%= @user.name %>'s Tweets </h1>
      </div>
        
        <% @tweets.each do |tweet| %>
          <% if tweet.user == @user %>

            <%= render tweet %>

          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<%= render 'form',
tweet: @tweet,
title: "Edit Tweet",
submit: 'Update Tweet' %>

app/views/tweets/index.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-4">
        <h1 class="title has-text-centered"> Tweets </h1>
      </div>

      <%= render @tweets, index_user: true %>

    </div>
</div>

app/views/tweets/new.html.erb
<%= render 'form',
tweet: @tweet,
title: "#{current_user.name} - New Tweet",
submit: 'Post Tweet' %>

app/views/tweets/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-4">
        <h1 class="title has-text-centered"> <%= @tweet.user.name %>'s Tweet </h1>
      </div>
    
      <%= render @tweet %>

      <%= render @tweet.comments %>

    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="miltiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-4">
        <h1 class="title has-text-centered">New User</h1>
      </div>
    </div>

    <% if @user.errors.any? %>
      <div id='error_explanation'>
        <h2>
          <%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:
        </h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="column is-4 is-offset-4">
      <%= form_with model: @user, local: true do |form| %>
        <div class="field">
          <%= form.label :name, class: 'label' %>
          <div class="control">
            <%= form.text_field :name, class: 'input', placeholder: 'Your name' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :email, class: 'label' %>
          <div class="control">
            <%= form.text_field :email, class: 'input', placeholder: 'Your email' %>
          </div>
        </div>
        
        <div class="field">
          <%= form.label :password, class: 'label' %>
          <p class="control has-icons-left">
            <%= form.text_field :password, class: 'input', type: 'password', placeholder: 'Password' %>            
            <span class="icon is-small is-left">
              <i class="fas fa-lock"></i>
            </span>
          </p>
        </div>

        <div class="field">
          <%= form.label :password_confirmation, class: 'label' %>
          <p class="control has-icons-left">
            <%= form.text_field :password_confirmation, class: 'input', type: 'password', placeholder: 'Confirm Password' %>
            <span class="icon is-small is-left">
              <i class="fas fa-lock"></i>
            </span>
          </p>
        </div>

        <div class="field">
          <p class="control">
            <%= form.submit 'Create User', class: 'button is-success' %>
            <%= link_to 'Cancel', users_signup_path, class: 'button is-danger' %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h3><%= @user.name %></h3>
        <p><%= @user.email %></p>
      </div>
    </div>
  </div>
</div>